"use client";

import { createContext, useContext, useState, type ReactNode } from "react";

export type Lang = "en" | "es" | "pt" | "de" | "fr" | "zh" | "ja";

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

const VALID_LANGS: Lang[] = ["en", "es", "pt", "de", "fr", "zh", "ja"];

function getInitialLang(): Lang {
  if (typeof window === "undefined") return "en";
  const params = new URLSearchParams(window.location.search);
  const urlLang = params.get("lang") as Lang | null;
  if (urlLang && VALID_LANGS.includes(urlLang)) return urlLang;
  return "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(getInitialLang);

  const t = (key: string): string => {
    const dict = translations[lang] ?? translations.en;
    return dict[key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ---------------------------------------------------------------------------
// Shared chat keys (used across all languages)
// ---------------------------------------------------------------------------
const chatKeys = {
  // Chat bot messages
  "chat.welcome": "",
  "chat.occasion": "",
  "chat.groupSize": "",
  "chat.date": "",
  "chat.email": "",
  "chat.phone": "",
  "chat.duration": "",
  "chat.addons": "",
  "chat.pickup": "",
  "chat.contact": "",
  "chat.summary": "",
  "chat.confirmation": "",
  "chat.noAddons": "",
  "chat.sendThis": "",
  // Chat UI
  "chat.header": "",
  "chat.yachtRentals": "",
  "chat.online": "",
  "chat.repliesIn": "",
  "chat.typing": "",
  "chat.back": "",
  "chat.restart": "",
  "chat.continue": "",
  "chat.skip": "",
  "chat.ok": "",
  "chat.sendRequest": "",
  "chat.sending": "",
  "chat.continueWhatsApp": "",
  "chat.or": "",
  "chat.planAnother": "",
  "chat.reviewQuote": "",
  "chat.chatOnWhatsApp": "",
  "chat.tapContinue": "",
  // Reactions
  "reaction.birthday": "",
  "reaction.bachelor": "",
  "reaction.sunset": "",
  "reaction.proposal": "",
  "reaction.corporate": "",
  "reaction.vibes": "",
  // Options - occasions
  "opt.birthday": "",
  "opt.bachelor": "",
  "opt.sunset": "",
  "opt.proposal": "",
  "opt.corporate": "",
  "opt.vibes": "",
  // Options - group sizes
  "opt.intimate": "",
  "opt.smallGroup": "",
  "opt.party": "",
  "opt.bigGroup": "",
  "opt.event": "",
  // Options - duration
  "opt.2hr": "",
  "opt.4hr": "",
  "opt.8hr": "",
  "opt.fullday": "",
  "opt.multiday": "",
  "opt.from": "",
  "opt.customQuote": "",
  // Options - addons
  "opt.photo": "",
  "opt.sushi": "",
  "opt.dj": "",
  "opt.bottles": "",
  "opt.jetski": "",
  "opt.transport": "",
  "opt.hookah": "",
  "opt.cigar": "",
  "opt.sax": "",
  "opt.none": "",
  // Options - pickup
  "opt.southbeach": "",
  "opt.brickell": "",
  "opt.downtown": "",
  "opt.aventura": "",
  "opt.balharbour": "",
  "opt.sunnyisles": "",
  "opt.self": "",
  // Summary
  "summary.yourCharter": "",
  "summary.occasion": "",
  "summary.guests": "",
  "summary.date": "",
  "summary.duration": "",
  "summary.addons": "",
  "summary.pickup": "",
  "summary.estimate": "",
  "summary.disclaimer": "",
  // Contact form
  "form.name": "",
  "form.phone": "",
  "form.email": "",
  "form.notes": "",
  "form.required": "",
  "form.validEmail": "",
};

// Just for type documentation — not used at runtime
void chatKeys;

// ---------------------------------------------------------------------------
// Translations
// ---------------------------------------------------------------------------
const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Chat messages
    "chat.welcome":
      "Welcome to Emerald Eyes Miami. Let's build your perfect day on the water.",
    "chat.occasion": "What's the occasion?",
    "chat.groupSize": "Great choice! How many guests?",
    "chat.date": "When are you thinking?",
    "chat.email": "What's your email? We'll send the quote there.",
    "chat.phone": "And your phone number?",
    "chat.duration": "How long on the water?",
    "chat.addons": "Want to make it unforgettable? Pick as many as you'd like:",
    "chat.pickup": "Where are you staying? We can pick you up.",
    "chat.contact": "Almost there. How do we reach you?",
    "chat.summary": "Here's your experience:",
    "chat.confirmation": "We'll confirm within 1 hour. Talk soon!",
    "chat.noAddons": "No add-ons for now",
    "chat.sendThis": "Send this request",
    // Chat UI
    "chat.header": "Emerald Eyes Miami",
    "chat.yachtRentals": "Yacht Rentals",
    "chat.online": "online",
    "chat.repliesIn": "replies in",
    "chat.typing": "typing...",
    "chat.back": "Back",
    "chat.restart": "restart",
    "chat.continue": "Continue",
    "chat.skip": "Skip",
    "chat.ok": "OK",
    "chat.sendRequest": "Send My Request",
    "chat.sending": "Sending...",
    "chat.continueWhatsApp": "Continue on WhatsApp",
    "chat.or": "or",
    "chat.planAnother": "Plan Another Trip",
    "chat.reviewQuote": "Review My Quote",
    "chat.chatOnWhatsApp": "Chat on WhatsApp",
    "chat.tapContinue": "tap Continue",
    // Occasion reactions
    "reaction.birthday": "Happy birthday! Let's make it one to remember.",
    "reaction.bachelor": "Oh it's going to be a movie. Let's set it up.",
    "reaction.sunset":
      "The golden hour on the water hits different. Great pick.",
    "reaction.proposal":
      "We love a good love story. Let's plan the perfect moment.",
    "reaction.corporate":
      "Impressive setting for impressive people. Let's talk details.",
    "reaction.vibes": "No agenda, just ocean. We got you.",
    // Options - occasions
    "opt.birthday": "Birthday",
    "opt.bachelor": "Bachelor/ette",
    "opt.sunset": "Sunset Date",
    "opt.proposal": "Proposal",
    "opt.corporate": "Corporate",
    "opt.vibes": "Just Vibes",
    // Options - group size subtitles
    "opt.intimate": "Intimate",
    "opt.smallGroup": "Small group",
    "opt.party": "Party",
    "opt.bigGroup": "Big group",
    "opt.event": "Event",
    // Options - duration
    "opt.2hr": "2 Hours",
    "opt.4hr": "4 Hours",
    "opt.8hr": "8 Hours",
    "opt.fullday": "Full Day",
    "opt.multiday": "Multi-Day",
    "opt.from": "from",
    "opt.customQuote": "Custom quote",
    // Options - addons
    "opt.photo": "Photo Package",
    "opt.sushi": "Sushi Chef",
    "opt.dj": "DJ / Music",
    "opt.bottles": "Bottle Service",
    "opt.jetski": "Jet Skis",
    "opt.transport": "Transport",
    "opt.hookah": "Hookah",
    "opt.cigar": "Cigar Lounge",
    "opt.sax": "Live Sax Player",
    "opt.none": "Keep It Simple",
    // Options - pickup
    "opt.southbeach": "South Beach",
    "opt.brickell": "Brickell",
    "opt.downtown": "Downtown",
    "opt.aventura": "Aventura",
    "opt.balharbour": "Bal Harbour",
    "opt.sunnyisles": "Sunny Isles",
    "opt.self": "I'll get there myself",
    // Summary
    "summary.yourCharter": "Your Charter",
    "summary.occasion": "Occasion",
    "summary.guests": "Guests",
    "summary.date": "Date",
    "summary.duration": "Duration",
    "summary.addons": "Add-ons",
    "summary.pickup": "Pickup",
    "summary.estimate": "Estimate",
    "summary.disclaimer":
      "Planning range. Final quote confirmed within 1 hour.",
    // Contact form
    "form.name": "Your name",
    "form.phone": "Phone number",
    "form.email": "Email",
    "form.notes": "Special requests (optional)",
    "form.required": "Required",
    "form.validEmail": "Enter a valid email",
    // Trust
    "trust.responds": "Responds in 1 hour",
    "trust.charters": "100+ charters/year",
    // Scroll
    "scroll.label": "Scroll",
    // Sasha section
    "sasha.role": "Partner & Director of Operations",
    "sasha.title": "Meet",
    "sasha.name": "Sasha",
    "sasha.p1":
      "A proud Miami resident, Sasha holds a degree in Merchant Marine Science and has spent her career on the water. As our partner and Director of Operations, she personally oversees every charter — from the first message to the moment you step back on the dock.",
    "sasha.p2.pre":
      "When she's not coordinating charters, you'll find her on a",
    "sasha.p2.jetski": "jet ski",
    "sasha.p2.mid":
      ", diving, or exploring the coastline she knows like the back of her hand. With",
    "sasha.p2.hundred": "over a hundred rentals a year",
    "sasha.p2.post":
      "across Biscayne Bay, Haulover, and the Gulf Stream, Sasha brings the kind of hands-on knowledge that only comes from",
    "sasha.p2.living": "living",
    "sasha.p2.end": "this life — not just managing it.",
    "sasha.quote":
      "My favorite part? Making sure every guest walks away saying it was the best day they've ever had on the water.",
    "sasha.badge1": "Merchant Marine Graduate",
    "sasha.badge2": "100+ Charters / Year",
    "sasha.badge3": "Miami Local & Water Enthusiast",
    // Below-fold sections
    "exp.title": "Experiences",
    "exp.subtitle":
      "Every charter is designed around your occasion. Pick one, or let us create something custom.",
    "sax.label": "Signature Add-On",
    "sax.title.pre": "Live ",
    "sax.title.highlight": "Sax",
    "sax.title.post": " on the Water",
    "sax.p1":
      "Imagine cruising through Biscayne Bay as the sun melts into the horizon — and a professional saxophonist sets the soundtrack to your evening. Smooth jazz, deep house remixes, or soulful melodies — the vibe is yours to choose.",
    "sax.p2":
      "Whether it's a sunset date, a proposal, or a night out with friends, live sax transforms your charter into something cinematic. It's the detail guests never expect — and never forget.",
    "sax.quote":
      "The moment the sax hit during golden hour, everyone just stopped and looked at each other. Pure magic.",
    "sax.badge1": "Professional Musician",
    "sax.badge2": "Perfect for Sunset Cruises",
    "sax.badge3": "Jazz, House & Soul",
    "sushi.label": "Signature Add-On",
    "sushi.title.pre": "Private ",
    "sushi.title.highlight": "Sushi Chef",
    "sushi.p1":
      "A dedicated sushi chef boards your yacht with the freshest ingredients Miami has to offer — and prepares an omakase-style experience right before your eyes. Nigiri, sashimi, specialty rolls, all crafted on deck while you cruise.",
    "sushi.p2":
      "Whether it's a corporate event, a birthday celebration, or an intimate date night, a live sushi bar elevates your charter into a five-star dining experience — surrounded by nothing but ocean and skyline.",
    "sushi.quote":
      "Fresh tuna, open water, sunset views. It doesn't get better than this.",
    "sushi.badge1": "Omakase-Style Service",
    "sushi.badge2": "Professional Chef On Board",
    "sushi.badge3": "Freshest Local Ingredients",
    "trust.uscg": "USCG Inspected",
    "trust.uscg.sub": "Fully compliant & safe vessels",
    "trust.captains": "Licensed Captains",
    "trust.captains.sub": "Experienced professional crew",
    "trust.location": "North Miami Based",
    "trust.location.sub": "Haulover, Aventura, Sunny Isles",
    "why.title": "Why Emerald Eyes",
    "why.1.title": "Curated, Not Generic",
    "why.1.text":
      "Every charter is tailored to your group, your vibe, your vision.",
    "why.2.title": "We Handle Everything",
    "why.2.text": "From pickup to playlist to photos — you just show up.",
    "why.3.title": "North Miami Native",
    "why.3.text":
      "We know these waters. Haulover, Biscayne, Sunny Isles, the Gulf Stream — this is home.",
    "how.title": "How It Works",
    "how.1.title": "Chat With Us",
    "how.1.text":
      "Tell us the occasion, group size, and date. We build a quote in minutes.",
    "how.2.title": "We Confirm",
    "how.2.text":
      "Get your custom itinerary with pricing, yacht details, and add-ons.",
    "how.3.title": "Board & Enjoy",
    "how.3.text":
      "We handle every detail. You just step aboard and make memories.",
  },

  es: {
    // Chat messages
    "chat.welcome":
      "Bienvenido a Emerald Eyes Miami. Vamos a crear tu dia perfecto en el agua.",
    "chat.occasion": "Cual es la ocasion?",
    "chat.groupSize": "Excelente eleccion! Cuantos invitados?",
    "chat.date": "Cuando estas pensando?",
    "chat.email": "Cual es tu email? Enviaremos la cotizacion ahi.",
    "chat.phone": "Y tu numero de telefono?",
    "chat.duration": "Cuanto tiempo en el agua?",
    "chat.addons": "Quieres hacerlo inolvidable? Elige los que quieras:",
    "chat.pickup": "Donde te hospedas? Podemos recogerte.",
    "chat.contact": "Ya casi. Como te contactamos?",
    "chat.summary": "Tu experiencia:",
    "chat.confirmation": "Confirmaremos en 1 hora. Hablamos pronto!",
    "chat.noAddons": "Sin extras por ahora",
    "chat.sendThis": "Enviar esta solicitud",
    // Chat UI
    "chat.header": "Emerald Eyes Miami",
    "chat.yachtRentals": "Alquiler de Yates",
    "chat.online": "en linea",
    "chat.repliesIn": "responde en",
    "chat.typing": "escribiendo...",
    "chat.back": "Atras",
    "chat.restart": "reiniciar",
    "chat.continue": "Continuar",
    "chat.skip": "Omitir",
    "chat.ok": "OK",
    "chat.sendRequest": "Enviar Mi Solicitud",
    "chat.sending": "Enviando...",
    "chat.continueWhatsApp": "Continuar en WhatsApp",
    "chat.or": "o",
    "chat.planAnother": "Planear Otro Viaje",
    "chat.reviewQuote": "Revisar Mi Cotizacion",
    "chat.chatOnWhatsApp": "Chatear en WhatsApp",
    "chat.tapContinue": "toca Continuar",
    // Occasion reactions
    "reaction.birthday": "Feliz cumpleanos! Vamos a hacerlo inolvidable.",
    "reaction.bachelor": "Va a ser de pelicula. Vamos a armarlo.",
    "reaction.sunset": "La hora dorada en el agua es otra cosa. Gran eleccion.",
    "reaction.proposal":
      "Nos encanta una buena historia de amor. Planifiquemos el momento perfecto.",
    "reaction.corporate":
      "Un escenario impresionante para gente impresionante.",
    "reaction.vibes": "Sin agenda, solo oceano. Te tenemos.",
    // Options - occasions
    "opt.birthday": "Cumpleanos",
    "opt.bachelor": "Despedida",
    "opt.sunset": "Atardecer",
    "opt.proposal": "Propuesta",
    "opt.corporate": "Corporativo",
    "opt.vibes": "Solo Vibras",
    // Options - group sizes
    "opt.intimate": "Intimo",
    "opt.smallGroup": "Grupo pequeno",
    "opt.party": "Fiesta",
    "opt.bigGroup": "Grupo grande",
    "opt.event": "Evento",
    // Options - duration
    "opt.2hr": "2 Horas",
    "opt.4hr": "4 Horas",
    "opt.8hr": "8 Horas",
    "opt.fullday": "Dia Completo",
    "opt.multiday": "Varios Dias",
    "opt.from": "desde",
    "opt.customQuote": "Cotizacion personalizada",
    // Options - addons
    "opt.photo": "Paquete de Fotos",
    "opt.sushi": "Chef de Sushi",
    "opt.dj": "DJ / Musica",
    "opt.bottles": "Servicio de Botellas",
    "opt.jetski": "Motos de Agua",
    "opt.transport": "Transporte",
    "opt.hookah": "Hookah",
    "opt.cigar": "Sala de Puros",
    "opt.sax": "Saxofonista en Vivo",
    "opt.none": "Mantenerlo Simple",
    // Options - pickup
    "opt.southbeach": "South Beach",
    "opt.brickell": "Brickell",
    "opt.downtown": "Downtown",
    "opt.aventura": "Aventura",
    "opt.balharbour": "Bal Harbour",
    "opt.sunnyisles": "Sunny Isles",
    "opt.self": "Llego por mi cuenta",
    // Summary
    "summary.yourCharter": "Tu Charter",
    "summary.occasion": "Ocasion",
    "summary.guests": "Invitados",
    "summary.date": "Fecha",
    "summary.duration": "Duracion",
    "summary.addons": "Extras",
    "summary.pickup": "Recogida",
    "summary.estimate": "Estimado",
    "summary.disclaimer":
      "Rango estimado. Cotizacion final confirmada en 1 hora.",
    // Contact form
    "form.name": "Tu nombre",
    "form.phone": "Numero de telefono",
    "form.email": "Correo electronico",
    "form.notes": "Solicitudes especiales (opcional)",
    "form.required": "Requerido",
    "form.validEmail": "Ingresa un email valido",
    // Trust
    "trust.responds": "Responde en 1 hora",
    "trust.charters": "100+ charters/ano",
    "scroll.label": "Desliza",
    // Sasha section
    "sasha.role": "Socia y Directora de Operaciones",
    "sasha.title": "Conoce a",
    "sasha.name": "Sasha",
    "sasha.p1":
      "Residente orgullosa de Miami, Sasha tiene un titulo en Ciencia de la Marina Mercante y ha dedicado su carrera al agua. Como nuestra socia y Directora de Operaciones, supervisa personalmente cada charter — desde el primer mensaje hasta que regresas al muelle.",
    "sasha.p2.pre":
      "Cuando no esta coordinando charters, la encontraras en una",
    "sasha.p2.jetski": "moto de agua",
    "sasha.p2.mid":
      ", buceando, o explorando la costa que conoce como la palma de su mano. Con",
    "sasha.p2.hundred": "mas de cien alquileres al ano",
    "sasha.p2.post":
      "en Biscayne Bay, Haulover y el Gulf Stream, Sasha trae el tipo de conocimiento practico que solo viene de",
    "sasha.p2.living": "vivir",
    "sasha.p2.end": "esta vida — no solo administrarla.",
    "sasha.quote":
      "Mi parte favorita? Asegurarme de que cada invitado se vaya diciendo que fue el mejor dia de su vida en el agua.",
    "sasha.badge1": "Graduada en Marina Mercante",
    "sasha.badge2": "100+ Charters / Ano",
    "sasha.badge3": "Local de Miami y Amante del Agua",
    "exp.title": "Experiencias",
    "exp.subtitle":
      "Cada charter esta disenado para tu ocasion. Elige uno, o dejanos crear algo a medida.",
    "sax.label": "Servicio Exclusivo",
    "sax.title.pre": "Sax ",
    "sax.title.highlight": "en Vivo",
    "sax.title.post": " en el Agua",
    "sax.p1":
      "Imagina navegar por Biscayne Bay mientras el sol se funde en el horizonte — y un saxofonista profesional pone la banda sonora de tu velada.",
    "sax.p2":
      "Ya sea una cita al atardecer, una propuesta o una noche con amigos, el sax en vivo transforma tu charter en algo cinematografico.",
    "sax.quote":
      "Cuando el sax sono durante la hora dorada, todos se miraron. Magia pura.",
    "sax.badge1": "Musico Profesional",
    "sax.badge2": "Perfecto para Atardeceres",
    "sax.badge3": "Jazz, House y Soul",
    "sushi.label": "Servicio Exclusivo",
    "sushi.title.pre": "Chef de ",
    "sushi.title.highlight": "Sushi Privado",
    "sushi.p1":
      "Un chef de sushi dedicado sube a tu yate con los ingredientes mas frescos de Miami — y prepara una experiencia estilo omakase ante tus ojos.",
    "sushi.p2":
      "Ya sea un evento corporativo, un cumpleanos o una cita intima, un bar de sushi en vivo eleva tu charter a una experiencia gastronomica de cinco estrellas.",
    "sushi.quote":
      "Atun fresco, mar abierto, vistas al atardecer. No hay nada mejor.",
    "sushi.badge1": "Servicio Estilo Omakase",
    "sushi.badge2": "Chef Profesional a Bordo",
    "sushi.badge3": "Ingredientes Locales Frescos",
    "trust.uscg": "Inspeccion USCG",
    "trust.uscg.sub": "Embarcaciones seguras y certificadas",
    "trust.captains": "Capitanes Licenciados",
    "trust.captains.sub": "Tripulacion profesional con experiencia",
    "trust.location": "Base en North Miami",
    "trust.location.sub": "Haulover, Aventura, Sunny Isles",
    "why.title": "Por Que Emerald Eyes",
    "why.1.title": "Curado, No Generico",
    "why.1.text": "Cada charter se adapta a tu grupo, tu estilo, tu vision.",
    "why.2.title": "Nos Encargamos de Todo",
    "why.2.text":
      "Desde el transporte hasta la playlist y las fotos — tu solo apareces.",
    "why.3.title": "Nativos de North Miami",
    "why.3.text":
      "Conocemos estas aguas. Haulover, Biscayne, Sunny Isles, el Gulf Stream — esto es casa.",
    "how.title": "Como Funciona",
    "how.1.title": "Escribenos",
    "how.1.text":
      "Dinos la ocasion, cuantos son y la fecha. Armamos tu cotizacion en minutos.",
    "how.2.title": "Confirmamos",
    "how.2.text":
      "Recibe tu itinerario personalizado con precios, detalles del yate y extras.",
    "how.3.title": "Sube a Bordo",
    "how.3.text":
      "Nosotros manejamos cada detalle. Tu solo sube y crea recuerdos.",
  },

  pt: {
    "chat.welcome":
      "Bem-vindo ao Emerald Eyes Miami. Vamos criar seu dia perfeito na agua.",
    "chat.occasion": "Qual e a ocasiao?",
    "chat.groupSize": "Otima escolha! Quantos convidados?",
    "chat.date": "Quando voce esta pensando?",
    "chat.email": "Qual e seu email? Enviaremos o orcamento por la.",
    "chat.phone": "E seu numero de telefone?",
    "chat.duration": "Quanto tempo na agua?",
    "chat.addons": "Quer tornar inesquecivel? Escolha quantos quiser:",
    "chat.pickup": "Onde voce esta hospedado? Podemos buscar voce.",
    "chat.contact": "Quase la. Como entramos em contato?",
    "chat.summary": "Sua experiencia:",
    "chat.confirmation": "Confirmaremos em 1 hora. Ate logo!",
    "chat.noAddons": "Sem extras por enquanto",
    "chat.sendThis": "Enviar esta solicitacao",
    "chat.header": "Emerald Eyes Miami",
    "chat.yachtRentals": "Aluguel de Iates",
    "chat.online": "online",
    "chat.repliesIn": "responde em",
    "chat.typing": "digitando...",
    "chat.back": "Voltar",
    "chat.restart": "reiniciar",
    "chat.continue": "Continuar",
    "chat.skip": "Pular",
    "chat.ok": "OK",
    "chat.sendRequest": "Enviar Meu Pedido",
    "chat.sending": "Enviando...",
    "chat.continueWhatsApp": "Continuar no WhatsApp",
    "chat.or": "ou",
    "chat.planAnother": "Planejar Outra Viagem",
    "chat.reviewQuote": "Revisar Meu Orcamento",
    "chat.chatOnWhatsApp": "Chat no WhatsApp",
    "chat.tapContinue": "toque Continuar",
    "trust.responds": "Responde em 1 hora",
    "trust.charters": "100+ charters/ano",
    "scroll.label": "Rolar",
    "reaction.birthday": "Feliz aniversario! Vamos tornar inesquecivel.",
    "reaction.bachelor": "Vai ser de cinema. Vamos montar.",
    "reaction.sunset": "A hora dourada na agua e outra coisa. Otima escolha.",
    "reaction.proposal":
      "Amamos uma boa historia de amor. Vamos planejar o momento perfeito.",
    "reaction.corporate":
      "Cenario impressionante para pessoas impressionantes.",
    "reaction.vibes": "Sem agenda, so oceano. Conte com a gente.",
    "opt.birthday": "Aniversario",
    "opt.bachelor": "Despedida",
    "opt.sunset": "Por do Sol",
    "opt.proposal": "Pedido",
    "opt.corporate": "Corporativo",
    "opt.vibes": "So Curtir",
    "opt.intimate": "Intimo",
    "opt.smallGroup": "Grupo pequeno",
    "opt.party": "Festa",
    "opt.bigGroup": "Grupo grande",
    "opt.event": "Evento",
    "opt.2hr": "2 Horas",
    "opt.4hr": "4 Horas",
    "opt.8hr": "8 Horas",
    "opt.fullday": "Dia Inteiro",
    "opt.multiday": "Varios Dias",
    "opt.from": "a partir de",
    "opt.customQuote": "Orcamento personalizado",
    "opt.photo": "Pacote de Fotos",
    "opt.sushi": "Chef de Sushi",
    "opt.dj": "DJ / Musica",
    "opt.bottles": "Servico de Garrafas",
    "opt.jetski": "Jet Skis",
    "opt.transport": "Transporte",
    "opt.hookah": "Narguilhe",
    "opt.cigar": "Lounge de Charutos",
    "opt.sax": "Saxofonista ao Vivo",
    "opt.none": "Manter Simples",
    "opt.southbeach": "South Beach",
    "opt.brickell": "Brickell",
    "opt.downtown": "Downtown",
    "opt.aventura": "Aventura",
    "opt.balharbour": "Bal Harbour",
    "opt.sunnyisles": "Sunny Isles",
    "opt.self": "Vou por conta propria",
    "summary.yourCharter": "Seu Charter",
    "summary.occasion": "Ocasiao",
    "summary.guests": "Convidados",
    "summary.date": "Data",
    "summary.duration": "Duracao",
    "summary.addons": "Extras",
    "summary.pickup": "Buscar",
    "summary.estimate": "Estimativa",
    "summary.disclaimer":
      "Faixa de planejamento. Orcamento final confirmado em 1 hora.",
    "form.name": "Seu nome",
    "form.phone": "Telefone",
    "form.email": "Email",
    "form.notes": "Pedidos especiais (opcional)",
    "form.required": "Obrigatorio",
    "form.validEmail": "Insira um email valido",
  },

  de: {
    "chat.welcome":
      "Willkommen bei Emerald Eyes Miami. Planen wir Ihren perfekten Tag auf dem Wasser.",
    "chat.occasion": "Was ist der Anlass?",
    "chat.groupSize": "Tolle Wahl! Wie viele Gaste?",
    "chat.date": "Wann denken Sie an?",
    "chat.email": "Ihre E-Mail? Wir senden das Angebot dorthin.",
    "chat.phone": "Und Ihre Telefonnummer?",
    "chat.duration": "Wie lange auf dem Wasser?",
    "chat.addons":
      "Mochten Sie es unvergesslich machen? Wahlen Sie beliebig viele:",
    "chat.pickup": "Wo sind Sie untergebracht? Wir konnen Sie abholen.",
    "chat.contact": "Fast geschafft. Wie erreichen wir Sie?",
    "chat.summary": "Ihr Erlebnis:",
    "chat.confirmation": "Bestatigung innerhalb 1 Stunde. Bis bald!",
    "chat.noAddons": "Keine Extras vorerst",
    "chat.sendThis": "Anfrage senden",
    "chat.header": "Emerald Eyes Miami",
    "chat.yachtRentals": "Yacht-Vermietung",
    "chat.online": "online",
    "chat.repliesIn": "antwortet in",
    "chat.typing": "schreibt...",
    "chat.back": "Zuruck",
    "chat.restart": "neustart",
    "chat.continue": "Weiter",
    "chat.skip": "Uberspringen",
    "chat.ok": "OK",
    "chat.sendRequest": "Anfrage Senden",
    "chat.sending": "Wird gesendet...",
    "chat.continueWhatsApp": "Weiter auf WhatsApp",
    "chat.or": "oder",
    "chat.planAnother": "Weitere Reise Planen",
    "chat.reviewQuote": "Angebot Prufen",
    "chat.chatOnWhatsApp": "Chat auf WhatsApp",
    "chat.tapContinue": "tippe Weiter",
    "trust.responds": "Antwortet in 1 Stunde",
    "trust.charters": "100+ Charters/Jahr",
    "scroll.label": "Scrollen",
    "reaction.birthday":
      "Alles Gute zum Geburtstag! Machen wir es unvergesslich.",
    "reaction.bachelor": "Das wird ein Film. Legen wir los.",
    "reaction.sunset":
      "Die goldene Stunde auf dem Wasser ist etwas Besonderes.",
    "reaction.proposal":
      "Wir lieben eine gute Liebesgeschichte. Planen wir den perfekten Moment.",
    "reaction.corporate": "Beeindruckende Kulisse fur beeindruckende Menschen.",
    "reaction.vibes": "Keine Agenda, nur Ozean. Wir haben Sie.",
    "opt.birthday": "Geburtstag",
    "opt.bachelor": "Junggesell/in",
    "opt.sunset": "Sonnenuntergang",
    "opt.proposal": "Heiratsantrag",
    "opt.corporate": "Firmenfeier",
    "opt.vibes": "Einfach Geniessen",
    "opt.intimate": "Intim",
    "opt.smallGroup": "Kleine Gruppe",
    "opt.party": "Party",
    "opt.bigGroup": "Grosse Gruppe",
    "opt.event": "Event",
    "opt.2hr": "2 Stunden",
    "opt.4hr": "4 Stunden",
    "opt.8hr": "8 Stunden",
    "opt.fullday": "Ganzer Tag",
    "opt.multiday": "Mehrere Tage",
    "opt.from": "ab",
    "opt.customQuote": "Individuelles Angebot",
    "opt.photo": "Foto-Paket",
    "opt.sushi": "Sushi-Koch",
    "opt.dj": "DJ / Musik",
    "opt.bottles": "Flaschenservice",
    "opt.jetski": "Jet Skis",
    "opt.transport": "Transport",
    "opt.hookah": "Shisha",
    "opt.cigar": "Zigarren-Lounge",
    "opt.sax": "Live-Saxophonist",
    "opt.none": "Einfach Halten",
    "opt.southbeach": "South Beach",
    "opt.brickell": "Brickell",
    "opt.downtown": "Downtown",
    "opt.aventura": "Aventura",
    "opt.balharbour": "Bal Harbour",
    "opt.sunnyisles": "Sunny Isles",
    "opt.self": "Ich komme selbst",
    "summary.yourCharter": "Ihr Charter",
    "summary.occasion": "Anlass",
    "summary.guests": "Gaste",
    "summary.date": "Datum",
    "summary.duration": "Dauer",
    "summary.addons": "Extras",
    "summary.pickup": "Abholung",
    "summary.estimate": "Schatzung",
    "summary.disclaimer":
      "Planungsbereich. Endgultiges Angebot innerhalb 1 Stunde.",
    "form.name": "Ihr Name",
    "form.phone": "Telefonnummer",
    "form.email": "E-Mail",
    "form.notes": "Sonderwunsche (optional)",
    "form.required": "Erforderlich",
    "form.validEmail": "Gultige E-Mail eingeben",
  },

  fr: {
    "chat.welcome":
      "Bienvenue chez Emerald Eyes Miami. Creons votre journee parfaite sur l'eau.",
    "chat.occasion": "Quelle est l'occasion ?",
    "chat.groupSize": "Excellent choix ! Combien d'invites ?",
    "chat.date": "Quand pensez-vous ?",
    "chat.email": "Votre email ? Nous y enverrons le devis.",
    "chat.phone": "Et votre numero de telephone ?",
    "chat.duration": "Combien de temps sur l'eau ?",
    "chat.addons":
      "Envie de rendre ca inoubliable ? Choisissez autant que vous voulez :",
    "chat.pickup": "Ou logez-vous ? Nous pouvons venir vous chercher.",
    "chat.contact": "Presque fini. Comment vous contacter ?",
    "chat.summary": "Votre experience :",
    "chat.confirmation": "Confirmation sous 1 heure. A bientot !",
    "chat.noAddons": "Pas d'extras pour le moment",
    "chat.sendThis": "Envoyer cette demande",
    "chat.header": "Emerald Eyes Miami",
    "chat.yachtRentals": "Location de Yachts",
    "chat.online": "en ligne",
    "chat.repliesIn": "repond en",
    "chat.typing": "ecrit...",
    "chat.back": "Retour",
    "chat.restart": "recommencer",
    "chat.continue": "Continuer",
    "chat.skip": "Passer",
    "chat.ok": "OK",
    "chat.sendRequest": "Envoyer Ma Demande",
    "chat.sending": "Envoi...",
    "chat.continueWhatsApp": "Continuer sur WhatsApp",
    "chat.or": "ou",
    "chat.planAnother": "Planifier un Autre Voyage",
    "chat.reviewQuote": "Revoir Mon Devis",
    "chat.chatOnWhatsApp": "Chat sur WhatsApp",
    "chat.tapContinue": "appuyez Continuer",
    "trust.responds": "Repond en 1 heure",
    "trust.charters": "100+ charters/an",
    "scroll.label": "Defiler",
    "reaction.birthday": "Joyeux anniversaire ! Rendons-le inoubliable.",
    "reaction.bachelor": "Ca va etre un film. Mettons tout en place.",
    "reaction.sunset": "L'heure doree sur l'eau, c'est magique. Super choix.",
    "reaction.proposal":
      "Nous adorons les belles histoires d'amour. Planifions le moment parfait.",
    "reaction.corporate":
      "Un cadre impressionnant pour des gens impressionnants.",
    "reaction.vibes": "Pas de programme, juste l'ocean.",
    "opt.birthday": "Anniversaire",
    "opt.bachelor": "Enterrement de vie",
    "opt.sunset": "Coucher de Soleil",
    "opt.proposal": "Demande en Mariage",
    "opt.corporate": "Entreprise",
    "opt.vibes": "Juste Profiter",
    "opt.intimate": "Intime",
    "opt.smallGroup": "Petit groupe",
    "opt.party": "Fete",
    "opt.bigGroup": "Grand groupe",
    "opt.event": "Evenement",
    "opt.2hr": "2 Heures",
    "opt.4hr": "4 Heures",
    "opt.8hr": "8 Heures",
    "opt.fullday": "Journee Entiere",
    "opt.multiday": "Plusieurs Jours",
    "opt.from": "a partir de",
    "opt.customQuote": "Devis personnalise",
    "opt.photo": "Forfait Photo",
    "opt.sushi": "Chef Sushi",
    "opt.dj": "DJ / Musique",
    "opt.bottles": "Service Bouteilles",
    "opt.jetski": "Jet Skis",
    "opt.transport": "Transport",
    "opt.hookah": "Chicha",
    "opt.cigar": "Salon Cigares",
    "opt.sax": "Saxophoniste Live",
    "opt.none": "Garder Simple",
    "opt.southbeach": "South Beach",
    "opt.brickell": "Brickell",
    "opt.downtown": "Downtown",
    "opt.aventura": "Aventura",
    "opt.balharbour": "Bal Harbour",
    "opt.sunnyisles": "Sunny Isles",
    "opt.self": "J'y vais moi-meme",
    "summary.yourCharter": "Votre Charter",
    "summary.occasion": "Occasion",
    "summary.guests": "Invites",
    "summary.date": "Date",
    "summary.duration": "Duree",
    "summary.addons": "Extras",
    "summary.pickup": "Prise en charge",
    "summary.estimate": "Estimation",
    "summary.disclaimer":
      "Fourchette indicative. Devis final confirme sous 1 heure.",
    "form.name": "Votre nom",
    "form.phone": "Telephone",
    "form.email": "Email",
    "form.notes": "Demandes speciales (facultatif)",
    "form.required": "Obligatoire",
    "form.validEmail": "Entrez un email valide",
  },

  zh: {
    "chat.welcome": "Emerald Eyes Miami. ",
    "chat.occasion": "",
    "chat.groupSize": "",
    "chat.date": "",
    "chat.email": "",
    "chat.phone": "",
    "chat.duration": "",
    "chat.addons": "",
    "chat.pickup": "",
    "chat.contact": "",
    "chat.summary": "",
    "chat.confirmation": "1",
    "chat.noAddons": "",
    "chat.sendThis": "",
    "chat.header": "Emerald Eyes Miami",
    "chat.yachtRentals": "",
    "chat.online": "",
    "chat.repliesIn": "",
    "chat.typing": "...",
    "chat.back": "",
    "chat.restart": "",
    "chat.continue": "",
    "chat.skip": "",
    "chat.ok": "",
    "chat.sendRequest": "",
    "chat.sending": "...",
    "chat.continueWhatsApp": "WhatsApp",
    "chat.or": "",
    "chat.planAnother": "",
    "chat.reviewQuote": "",
    "chat.chatOnWhatsApp": "WhatsApp聊天",
    "chat.tapContinue": "点击继续",
    "trust.responds": "1小时内回复",
    "trust.charters": "每年100+包船",
    "scroll.label": "滚动",
    "reaction.birthday": "生日快乐！让我们让它难以忘怀。",
    "reaction.bachelor": "派对即将上演。让我们开始吧。",
    "reaction.sunset": "水上日落别有一番风味。好选择。",
    "reaction.proposal": "我们热爱浪漫故事。让我们策划完美时刻。",
    "reaction.corporate": "令人印象深刻的场景。",
    "reaction.vibes": "没有计划，只有大海。交给我们。",
    "opt.birthday": "生日",
    "opt.bachelor": "单身派对",
    "opt.sunset": "日落",
    "opt.proposal": "求婚",
    "opt.corporate": "商务",
    "opt.vibes": "随性",
    "opt.intimate": "私密",
    "opt.smallGroup": "小团",
    "opt.party": "派对",
    "opt.bigGroup": "大团",
    "opt.event": "活动",
    "opt.2hr": "2小时",
    "opt.4hr": "4小时",
    "opt.8hr": "8小时",
    "opt.fullday": "全天",
    "opt.multiday": "多天",
    "opt.from": "起价",
    "opt.customQuote": "定制报价",
    "opt.photo": "摄影套餐",
    "opt.sushi": "寿司主厨",
    "opt.dj": "DJ / 音乐",
    "opt.bottles": "酒水服务",
    "opt.jetski": "摩托艇",
    "opt.transport": "接送",
    "opt.hookah": "水烟",
    "opt.cigar": "雪茄吧",
    "opt.sax": "萨克斯手",
    "opt.none": "保持简单",
    "opt.southbeach": "South Beach",
    "opt.brickell": "Brickell",
    "opt.downtown": "Downtown",
    "opt.aventura": "Aventura",
    "opt.balharbour": "Bal Harbour",
    "opt.sunnyisles": "Sunny Isles",
    "opt.self": "自行前往",
    "summary.yourCharter": "您的包船",
    "summary.occasion": "场合",
    "summary.guests": "宾客",
    "summary.date": "日期",
    "summary.duration": "时长",
    "summary.addons": "附加项",
    "summary.pickup": "接送",
    "summary.estimate": "估价",
    "summary.disclaimer": "预估范围。最终报价1小时内确认。",
    "form.name": "您的姓名",
    "form.phone": "电话号码",
    "form.email": "邮箱",
    "form.notes": "特殊要求 (可选)",
    "form.required": "必填",
    "form.validEmail": "请输入有效邮箱",
  },

  ja: {
    "chat.welcome": "Emerald Eyes Miami. ",
    "chat.occasion": "",
    "chat.groupSize": "",
    "chat.date": "",
    "chat.email": "",
    "chat.phone": "",
    "chat.duration": "",
    "chat.addons": "",
    "chat.pickup": "",
    "chat.contact": "",
    "chat.summary": "",
    "chat.confirmation": "1",
    "chat.noAddons": "",
    "chat.sendThis": "",
    "chat.header": "Emerald Eyes Miami",
    "chat.yachtRentals": "",
    "chat.online": "",
    "chat.repliesIn": "",
    "chat.typing": "...",
    "chat.back": "",
    "chat.restart": "",
    "chat.continue": "",
    "chat.skip": "",
    "chat.ok": "OK",
    "chat.sendRequest": "",
    "chat.sending": "...",
    "chat.continueWhatsApp": "WhatsApp",
    "chat.or": "",
    "chat.planAnother": "",
    "chat.reviewQuote": "",
    "chat.chatOnWhatsApp": "WhatsAppでチャット",
    "chat.tapContinue": "続けるをタップ",
    "trust.responds": "1時間以内に返信",
    "trust.charters": "年間100+チャーター",
    "scroll.label": "スクロール",
    "reaction.birthday": "お誕生日おめでとう！忘れられない日にしましょう。",
    "reaction.bachelor": "最高の時間になります。準備しましょう。",
    "reaction.sunset": "水上のサンセットは格別です。素晴らしい選択。",
    "reaction.proposal": "ロマンチックですね。完璧な瞬間を計画しましょう。",
    "reaction.corporate": "印象的な場所で印象的なイベントを。",
    "reaction.vibes": "予定なし、ただ海だけ。お任せください。",
    "opt.birthday": "誕生日",
    "opt.bachelor": "独身パーティー",
    "opt.sunset": "サンセット",
    "opt.proposal": "プロポーズ",
    "opt.corporate": "法人",
    "opt.vibes": "気ままに",
    "opt.intimate": "少人数",
    "opt.smallGroup": "小グループ",
    "opt.party": "パーティー",
    "opt.bigGroup": "大グループ",
    "opt.event": "イベント",
    "opt.2hr": "2時間",
    "opt.4hr": "4時間",
    "opt.8hr": "8時間",
    "opt.fullday": "終日",
    "opt.multiday": "複数日",
    "opt.from": "〜から",
    "opt.customQuote": "カスタム見積",
    "opt.photo": "フォトパッケージ",
    "opt.sushi": "寿司シェフ",
    "opt.dj": "DJ / 音楽",
    "opt.bottles": "ボトルサービス",
    "opt.jetski": "ジェットスキー",
    "opt.transport": "送迎",
    "opt.hookah": "シーシャ",
    "opt.cigar": "シガーラウンジ",
    "opt.sax": "ライブサックス",
    "opt.none": "シンプルに",
    "opt.southbeach": "South Beach",
    "opt.brickell": "Brickell",
    "opt.downtown": "Downtown",
    "opt.aventura": "Aventura",
    "opt.balharbour": "Bal Harbour",
    "opt.sunnyisles": "Sunny Isles",
    "opt.self": "自分で行きます",
    "summary.yourCharter": "チャーター内容",
    "summary.occasion": "目的",
    "summary.guests": "ゲスト",
    "summary.date": "日付",
    "summary.duration": "時間",
    "summary.addons": "追加オプション",
    "summary.pickup": "送迎",
    "summary.estimate": "見積",
    "summary.disclaimer": "概算範囲。最終見積は1時間以内に確認。",
    "form.name": "お名前",
    "form.phone": "電話番号",
    "form.email": "メール",
    "form.notes": "特別なリクエスト (任意)",
    "form.required": "必須",
    "form.validEmail": "有効なメールを入力",
  },
};
